import { Injectable } from '@nestjs/common';

const data = [
  {
    globalFundCode: 'SSGILP_AEQF',
    shareClassId: 'AEQF',
    productLine: 'ILP',
    asOfDate: '2025-01-10',
    asOfDateVal: '2025-01-10T00:00:00.000Z',
    currency: 'USD',
    prevValue: null,
    value: null,
    prevPrice: null,
    price: 915,
    createdBy: 'ApiPriceSgLifeco.updatePwsWithHistorical',
    createdByFct: 'ApiPriceSgLifeco.updatePwsWithHistorical',
    createdAt: '2025-12-08T01:55:01.778Z',
    sourceCode: null,
    source: 'eDM',
    offer3Price: null,
    offer5Price: null,
    offerPrice: null,
    changePrice: null,
    changePercent: null,
  },
  {
    globalFundCode: 'SSGILP_BFIX',
    shareClassId: 'BFIX',
    productLine: 'ILP',
    asOfDate: '2025-01-11',
    asOfDateVal: '2025-01-11T00:00:00.000Z',
    currency: 'HKD',
    prevValue: null,
    value: null,
    prevPrice: null,
    price: 370,
    createdBy: 'DenormalizePwsSgLifeco.processGapfill',
    createdByFct: 'DenormalizePwsSgLifeco.processGapfill',
    createdAt: '2025-12-08T01:55:01.822Z',
    sourceCode: 'GAPFILL',
    source: 'eDM',
    offer3Price: null,
    offer5Price: null,
    offerPrice: null,
    changePrice: null,
    changePercent: 0,
  },
  {
    globalFundCode: 'SSGILP_CGRO',
    shareClassId: 'CGRO',
    productLine: 'ILP',
    asOfDate: '2025-01-12',
    asOfDateVal: '2025-01-12T00:00:00.000Z',
    currency: 'EUR',
    prevValue: null,
    value: null,
    prevPrice: null,
    price: 142,
    createdBy: 'DenormalizePwsSgLifeco.processGapfill',
    createdByFct: 'DenormalizePwsSgLifeco.processGapfill',
    createdAt: '2025-12-08T01:55:01.830Z',
    sourceCode: 'GAPFILL',
    source: 'eDM',
    offer3Price: null,
    offer5Price: null,
    offerPrice: null,
    changePrice: null,
    changePercent: 0,
  },
  {
    globalFundCode: 'SSGILP_DVID',
    shareClassId: 'DVID',
    productLine: 'ILP',
    asOfDate: '2025-01-13',
    asOfDateVal: '2025-01-13T00:00:00.000Z',
    currency: 'SGD',
    prevValue: null,
    value: null,
    prevPrice: null,
    price: 217,
    createdBy: 'ApiPriceSgLifeco.updatePwsWithHistorical',
    createdByFct: 'ApiPriceSgLifeco.updatePwsWithHistorical',
    createdAt: '2025-12-08T01:55:01.809Z',
    sourceCode: null,
    source: 'eDM',
    offer3Price: null,
    offer5Price: null,
    offerPrice: null,
    changePrice: null,
    changePercent: null,
  },
  {
    globalFundCode: 'SSGILP_EMRG',
    shareClassId: 'EMRG',
    productLine: 'ILP',
    asOfDate: '2025-01-14',
    asOfDateVal: '2025-01-14T00:00:00.000Z',
    currency: 'USD',
    prevValue: null,
    value: null,
    prevPrice: null,
    price: 509,
    createdBy: 'ApiPriceSgLifeco.updatePwsWithHistorical',
    createdByFct: 'ApiPriceSgLifeco.updatePwsWithHistorical',
    createdAt: '2025-12-08T01:55:01.840Z',
    sourceCode: null,
    source: 'eDM',
    offer3Price: null,
    offer5Price: null,
    offerPrice: null,
    changePrice: null,
    changePercent: null,
  },
  {
    globalFundCode: 'SSGILP_FBAL',
    shareClassId: 'FBAL',
    productLine: 'ILP',
    asOfDate: '2025-01-15',
    asOfDateVal: '2025-01-15T00:00:00.000Z',
    currency: 'HKD',
    prevValue: null,
    value: null,
    prevPrice: null,
    price: 341,
    createdBy: 'ApiPriceSgLifeco.updatePwsWithHistorical',
    createdByFct: 'ApiPriceSgLifeco.updatePwsWithHistorical',
    createdAt: '2025-12-08T01:55:01.851Z',
    sourceCode: null,
    source: 'eDM',
    offer3Price: null,
    offer5Price: null,
    offerPrice: null,
    changePrice: null,
    changePercent: null,
  },
  {
    globalFundCode: 'SSGILP_GINT',
    shareClassId: 'GINT',
    productLine: 'ILP',
    asOfDate: '2025-01-16',
    asOfDateVal: '2025-01-16T00:00:00.000Z',
    currency: 'EUR',
    prevValue: null,
    value: null,
    prevPrice: null,
    price: 370,
    createdBy: 'ApiPriceSgLifeco.updatePwsWithHistorical',
    createdByFct: 'ApiPriceSgLifeco.updatePwsWithHistorical',
    createdAt: '2025-12-08T01:55:01.866Z',
    sourceCode: null,
    source: 'eDM',
    offer3Price: null,
    offer5Price: null,
    offerPrice: null,
    changePrice: null,
    changePercent: null,
  },
  {
    globalFundCode: 'SSGILP_HINC',
    shareClassId: 'HINC',
    productLine: 'ILP',
    asOfDate: '2025-01-17',
    asOfDateVal: '2025-01-17T00:00:00.000Z',
    currency: 'SGD',
    prevValue: null,
    value: null,
    prevPrice: null,
    price: 741,
    createdBy: 'ApiPriceSgLifeco.updatePwsWithHistorical',
    createdByFct: 'ApiPriceSgLifeco.updatePwsWithHistorical',
    createdAt: '2025-12-08T01:55:01.883Z',
    sourceCode: null,
    source: 'eDM',
    offer3Price: null,
    offer5Price: null,
    offerPrice: null,
    changePrice: null,
    changePercent: null,
  },
  {
    globalFundCode: 'SSGILP_JVAL',
    shareClassId: 'JVAL',
    productLine: 'ILP',
    asOfDate: '2025-01-18',
    asOfDateVal: '2025-01-18T00:00:00.000Z',
    currency: 'USD',
    prevValue: null,
    value: null,
    prevPrice: null,
    price: 269,
    createdBy: 'DenormalizePwsSgLifeco.processGapfill',
    createdByFct: 'DenormalizePwsSgLifeco.processGapfill',
    createdAt: '2025-12-08T01:55:01.918Z',
    sourceCode: 'GAPFILL',
    source: 'eDM',
    offer3Price: null,
    offer5Price: null,
    offerPrice: null,
    changePrice: null,
    changePercent: 0,
  },
  {
    globalFundCode: 'SSGILP_KGTH',
    shareClassId: 'KGTH',
    productLine: 'ILP',
    asOfDate: '2025-01-19',
    asOfDateVal: '2025-01-19T00:00:00.000Z',
    currency: 'HKD',
    prevValue: null,
    value: null,
    prevPrice: null,
    price: 361,
    createdBy: 'DenormalizePwsSgLifeco.processGapfill',
    createdByFct: 'DenormalizePwsSgLifeco.processGapfill',
    createdAt: '2025-12-08T01:55:01.929Z',
    sourceCode: 'GAPFILL',
    source: 'eDM',
    offer3Price: null,
    offer5Price: null,
    offerPrice: null,
    changePrice: null,
    changePercent: 0,
  },
];

@Injectable()
export class AssetsService {
  /**
   * Get all assets for a user
   */
  getAllAssets(): any {
    try {
      const portfolios = data;

      return portfolios;
    } catch (error) {
      console.error('Error fetching portfolios:', error);
      throw new Error('Failed to fetch portfolios');
    }
  }
}
